name: 🚀 Deployment

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: path to application working directory
        required: true
  workflow_dispatch:
    inputs:
      working-directory:
        description: path to application working directory
        required: true
        type: choice
        options:
        - apps/backend
        - apps/frontend

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  typecheck:
    uses: ./.github/workflows/typecheck.yml
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    name: 🚀 Deploy to Fly
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 🚀 Deploy
        run: flyctl deploy ${{ inputs.working-directory }} --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
